name: Build Portable Privoxy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install autoconf automake pcre
          # 确保PCRE头文件可以被找到
          export CPPFLAGS="-I$(brew --prefix pcre)/include"
          export LDFLAGS="-L$(brew --prefix pcre)/lib"
          echo "CPPFLAGS=-I$(brew --prefix pcre)/include" >> $GITHUB_ENV
          echo "LDFLAGS=-L$(brew --prefix pcre)/lib" >> $GITHUB_ENV
      
      - name: Install dependencies on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libpcre3-dev libpcre3 pcre3-utils build-essential zlib1g-dev
          # 验证PCRE安装
          dpkg -L libpcre3-dev | grep -E "(pcre\.h|pcreposix\.h)"
      
      - name: Download Privoxy source
        run: |
          PRIVOXY_VERSION="3.0.34"
          # 使用正确的 SourceForge 下载链接
          wget "https://sourceforge.net/projects/ijbswa/files/Sources/3.0.34%20%28stable%29/privoxy-3.0.34-stable-src.tar.gz/download" -O privoxy.tar.gz
          tar -xzf privoxy.tar.gz
          mv privoxy-3.0.34-stable privoxy-src
      
      - name: Configure and compile Privoxy
        run: |
          cd privoxy-src
          autoheader
          autoconf
          
          # 为macOS设置配置参数
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            ./configure \
              --enable-static \
              --with-pcre="$(brew --prefix pcre)" \
              CPPFLAGS="-I$(brew --prefix pcre)/include" \
              LDFLAGS="-L$(brew --prefix pcre)/lib"
          else
            ./configure --enable-static
          fi
          
          make
      
      - name: Verify build
        run: |
          cd privoxy-src
          ls -la privoxy
          ./privoxy --version || echo "Version check failed, but binary exists"
      
      - name: Modify Privoxy configuration
        run: |
          cd privoxy-src
          cp config default.config
          
          # 修改配置文件，让Privoxy监听所有网络接口
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            sed -i '.bak' 's/^listen-address  127.0.0.1:8118/listen-address  0.0.0.0:8118/' default.config
            sed -i '.bak' 's/^listen-address  \[::1\]:8118/#listen-address  [::1]:8118/' default.config
          else
            sed -i 's/^listen-address  127.0.0.1:8118/listen-address  0.0.0.0:8118/' default.config
            sed -i 's/^listen-address  \[::1\]:8118/#listen-address  [::1]:8118/' default.config
          fi
          
          echo "验证配置修改："
          grep "listen-address" default.config | head -5
      
      - name: Create packaging directory
        run: |
          mkdir privoxy-package
          cd privoxy-src
          
          # 复制必要文件
          cp privoxy ../privoxy-package/
          cp default.config ../privoxy-package/
          
          # 复制其他必要的配置文件
          cp -r templates ../privoxy-package/ || echo "No templates directory"
          cp *.action ../privoxy-package/ || echo "No action files"
          cp *.filter ../privoxy-package/ || echo "No filter files"
          
          # 创建启动脚本
          cat > ../privoxy-package/start-privoxy.sh << 'EOF'
          #!/bin/bash
          DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
          echo "Starting Privoxy on 0.0.0.0:8118..."
          echo "Access via: http://127.0.0.1:8118"
          echo "Press Ctrl+C to stop"
          echo ""
          cd "$DIR"
          ./privoxy ./default.config
          EOF
          chmod +x ../privoxy-package/start-privoxy.sh
          
          # 创建README文件
          cat > ../privoxy-package/README.txt << 'EOF'
          Privoxy Portable Version
          ========================
          
          Quick Start:
          1. Run: ./start-privoxy.sh
          2. Configure your browser HTTP proxy to: 127.0.0.1:8118
          3. Or use as network proxy server: YOUR_COMPUTER_IP:8118
          
          Files:
          - privoxy: Main executable
          - default.config: Configuration file (listens on 0.0.0.0:8118)
          - start-privoxy.sh: Startup script
          - *.action: Action files for filtering rules
          - *.filter: Filter files for content filtering
          - templates/: HTML templates for error pages
          
          Configuration:
          This version is configured to listen on all network interfaces (0.0.0.0:8118)
          which means other devices on your network can use it as a proxy.
          
          Usage:
          - Local proxy: 127.0.0.1:8118
          - Network proxy: YOUR_IP:8118 (accessible from other devices)
          
          To stop: Press Ctrl+C in the terminal where it's running
          
          Web interface: http://127.0.0.1:8118 (when running)
          EOF
      
      - name: Package Privoxy for macOS
        if: runner.os == 'macOS'
        run: |
          cd privoxy-package
          ls -la
          cd ..
          tar -czf privoxy-portable-macos.tar.gz -C privoxy-package .
      
      - name: Package Privoxy for Linux
        if: runner.os == 'Linux'
        run: |
          cd privoxy-package
          ls -la
          cd ..
          tar -czf privoxy-portable-linux.tar.gz -C privoxy-package .
      
      - name: Upload Privoxy artifact
        uses: actions/upload-artifact@v4
        with:
          name: privoxy-portable-${{ runner.os }}
          path: |
            privoxy-portable-*.tar.gz
          if-no-files-found: error
